name: base
channels:
  - defaults
  - bioconda
  - r
  - biobuilds
  - conda-forge
dependencies:
  - r=4.2
  - fastp=0.23.4
  - bwa=0.7.18
  - samtools=1.20
  - picard=2.21.3
  - r-gsheet
  - r-fuzzyjoin
  - r-tidyverse